### ISSUE TITLE
Make less mysterious. 

### ISSUE THREAD

**Issue by ChrisMcKee** [benaadams/Ben.Demystifier#1]

**Comment by benaadams** [comment]
![Mystery-Intensifies](https://memegenerator.net/img/instances/53045526/mystery-intensifies.jpg)

**Comment by ChrisMcKee** [comment]
![](https://media.giphy.com/media/i765Bu9QP2wYo/giphy.gif)

**Comment by benaadams** [comment]
Updated readme.md :)

**Comment by CADbloke** [comment]
![](https://media.giphy.com/media/wfOe7SdZ3XyHm/giphy.gif)
