### ISSUE TITLE
ArgumentOutOfRange when processing a nested type of a generic type

### ISSUE THREAD

**Issue by KirillOsenkov** [benaadams/Ben.Demystifier#109]
| String.Substring Line 1282
-- | --
  | TypeNameHelper.GetTypeNameForGenericType Line 65
  | ValueTupleResolvedParameter.AppendTypeName Line 23
  | ResolvedParameter.Append Line 34
  | ResolvedMethod.Append Line 93
  | EnhancedStackTrace.Append Line 103
  | EnhancedStackTrace.ToString Line 84

The exception is here:
https://github.com/benaadams/Ben.Demystifier/blob/0f17b3029b842b0886ce49cafc3032184805873e/src/Ben.Demystifier/TypeNameHelper.cs#L65

The type in question is:
`Roslyn.Utilities.MultiDictionary`2+ValueSet[Microsoft.CodeAnalysis.Document,System.ValueTuple`2[Microsoft.CodeAnalysis.ISymbol,Microsoft.CodeAnalysis.FindSymbols.Finders.IReferenceFinder]]`

http://sourceroslyn.io/#Microsoft.CodeAnalysis/InternalUtilities/MultiDictionary.cs,b9e522a001545166

Even though the type is a generic type, the name is just `ValueSet` and doesn't contains the backtick.

**Comment by KirillOsenkov** [comment]
Here's a PR that adds a unit-test:
https://github.com/benaadams/Ben.Demystifier/pull/110

It is significant that the method parameter type is a nested type of a generic type where the generic type parameter is a value tuple with named parameters.

**Comment by KirillOsenkov** [comment]
Basically the logic for value tuples needs to be aware of nested types of generic types that themselves don't have a backtick in the name: https://github.com/benaadams/Ben.Demystifier/blob/0f17b3029b842b0886ce49cafc3032184805873e/src/Ben.Demystifier/ValueTupleResolvedParameter.cs#L23-L26

**Comment by benaadams** [comment]
Released a new version that doesn't have this issue; though not sure it makes it a sensible type name, looking into that
