### ISSUE TITLE
ValueTaskAwaiter no longer annotated with StackTraceHidden

### ISSUE THREAD

**Issue by bruno-garcia** [benaadams/Ben.Demystifier#118]
Running against .NET 5, the test `MixedStack` fails as a new frame shows up:

`TResult System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()`.

In [this change to the runtime (corefx)](https://github.com/dotnet/coreclr/pull/14652) you've added the attributes but it seems like [it's are gone now](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/ValueTaskAwaiter.cs#L44).

The current approach is to either rely on the attribute or fallback to the type checks:
https://github.com/benaadams/Ben.Demystifier/blob/87375e9013db462ad5af21bc308bc73c63cfe919/src/Ben.Demystifier/EnhancedStackTrace.Frames.cs#L665-L703

I could open a PR that removes the `if` and tries both strategies. Let me know if this is the approach you want to take, or another?

**Comment by benaadams** [comment]
Ah; made a change so the runtime also hid stacks marked with `MethodImplOptions.AggressiveInlining` which is detected with
`mb.MethodImplementationFlags & MethodImplAttributes.AggressiveInlining`; which meant `StackTraceHidden` wasn't needed for these methods. 

https://github.com/dotnet/runtime/blob/7c18d4d6488dab82124d475d1199def01d1d252c/src/libraries/System.Private.CoreLib/src/System/Diagnostics/StackTrace.cs#L348-L361

So probably should take the same approach?
