### ISSUE TITLE
Thoughts on `<Nullable>enable</Nullable>` ?

### ISSUE THREAD

**Issue by bruno-garcia** [benaadams/Ben.Demystifier#126]
What are you thoughts on enabling nullability checks?
Would remove the `Debug.Assert`s in the process. Make porting code from the runtime easier.

**Comment by benaadams** [comment]
Am happy with it though looks like has targeting issues? https://github.com/benaadams/Ben.Demystifier/pull/125#issuecomment-753649679

**Comment by bruno-garcia** [comment]
@benaadams I copied code over which is annotated and didn't remove it. Will do now.

Adding NRT would land as a separate PR then. 👍

**Comment by bruno-garcia** [comment]
#136
