### ISSUE TITLE
Add .pdb files to GitHub & NuGet releases

### ISSUE THREAD

**Issue by ghost** [benaadams/Ben.Demystifier#142]
I have to debug this library and all I have is the `.dll` (no `.pdb`, so I'm unable to debug in rider). It would be nice if the `pdb` came with the `dll` so I don't have to build it myself to be able to debug it.

**Comment by samtrion** [comment]
The project already supports SourceLink for Github, so this should not be a problem.

**Comment by benaadams** [comment]
As well as the source and sourcelink the pdb is embedded in the dll so it should be debuggable?

![image](https://user-images.githubusercontent.com/1142958/103896830-79257780-50ea-11eb-8b63-1aef48f24aae.png)

**Comment by ghost** [comment]
That is very strange... Every time I've tried to debug I always get 'could not resolve method' and my breakpoints are never hit. One thing though is that I'm using it with Unity so there's possibly a chance of that causing some issues.

The main reason I've been trying to debug is because whenever I try to `.Demistify()` exceptions nothing changes, and I was trying to figure out why, Some of your other code works though (like `new EnhancedStackTrace(oldStackTrace)` and `stringBuilder.AppendTypeDisplayName()`).

**Comment by bruno-garcia** [comment]
@EternalClickbait what are you using for debugging? Visual Studio, Rider? And what version?

**Comment by ghost** [comment]
> @EternalClickbait what are you using for debugging? Visual Studio, Rider? And what version?

Rider, 2020.2.4, I'm usingBen.Demistyfier 0.1.6 (what my package manager automatically game me)
@bruno-garcia

**Comment by ghost** [comment]
Update: I'm unable to break at most lines. The only 2 I'm able to are the beginning/entrance of the method, and the start of the `try` block.
![image](https://user-images.githubusercontent.com/48875125/105969722-4c0a2a80-60d4-11eb-8be7-a05b73a5fa53.png)

Update 2: 
The debugging and breakpoints are.....funky. The editor breaks but at the wrong locations:
![image](https://user-images.githubusercontent.com/48875125/105974307-7e6a5680-60d9-11eb-9f7f-04b3f9e5e832.png)
I set the breakpoint at the entry of the `try`, it supposedly broke at the entrance to `System.Diagnostics.StringBuilderExtentions.AppendDemystified(this StringBuilder builder, Exception exception)`, but the stack shows the `ctor` for a `System.Diagnostics.ValueTupleResolvedParameter`. It also repeatedly breaks multiple times, even when the method is called only once (I've made sure of it).

**Comment by ghost** [comment]
@bruno-garcia @benaadams  @samtrion 

I think it was probably an issue caused by an old version of this library. I updated Rider to 2020.3.0 which did nothing, but as soon as I updated the library to 0.3.0, I immediately got my nice lovely stack traces back, and was able to debug properly. I'm now going to close this issue as I believe it is solved.
![image](https://user-images.githubusercontent.com/48875125/108321543-0e4e7c80-7210-11eb-8c7b-d47be98d9db0.png)

![image](https://user-images.githubusercontent.com/48875125/108321598-1d352f00-7210-11eb-81a5-0030d3fea3e9.png)
