### ISSUE TITLE
Why is Sample in language version 7.2?

### ISSUE THREAD

**Issue by satano** [benaadams/Ben.Demystifier#19]
Hello

Just a question. Why is sample project in [language version 7.2](https://github.com/benaadams/Ben.Demystifier/blob/master/sample/StackTrace/StackTrace.csproj#L13)? This is super last version and I am not sure who really has it. Probably most of the people will not compile it. The only place which is needed by 7.2 version is [`static string RefMethod(in string value)`](https://github.com/benaadams/Ben.Demystifier/blob/master/sample/StackTrace/Program.cs#L105).

**Comment by benaadams** [comment]
To show it converts the latest C# features back to their original form.

Might provide a better simpler sample as well

**Comment by satano** [comment]
Thanks
