### ISSUE TITLE
Strong-Naming the assembly

### ISSUE THREAD

**Issue by nicolaihenriksen** [benaadams/Ben.Demystifier#30]
What are the odds of you strong-naming the assembly anytime soon?

I can get around it by repackaging the nuget, but I would rather use yours directly so I can pull updates easily.

**Comment by nblumhardt** [comment]
https://github.com/dsplaisted/strongnamer may be able to help you in the meantime, @nicolaihenriksen

**Comment by nicolaihenriksen** [comment]
@nblumhardt cool! I'll have a look at that, sounds promising!

**Comment by CADbloke** [comment]
fyi background info: MahApps on String Naming https://github.com/MahApps/MahApps.Metro/issues/3029

tldr; computer says no.

**Comment by nicolaihenriksen** [comment]
@CADbloke I am aware of that :-) Which is also why if @benaadams decides that he does not want to do this, it is perfectly fine; I don't have a strong opinion on the subject of strongnaming. If I can get the strongnamer, which @nblumhardt mentioned, to work, well then there really is no issue at all.

I am currently working on a project where the whole stack is strong named, for historical reasons (I guess), that's why I opened this issue.

**Comment by 304NotModified** [comment]
I would recommend to strong name, but only to change it with a major version. Eg strong name only with 1.0.0.0 for all 1.x.y

It works very well with NLog, but beware that semver is a requirement.

**Comment by quigamdev** [comment]
@benaadams We would like to accept PR in https://github.com/riganti/dotvvm  with integration of this project, but we cannot do that before the assembly is strongly-named. 
It is not an option to use https://github.com/dsplaisted/strongnamer for us. 
Is there any plan to complete this issue?

**Comment by benaadams** [comment]
Try latest: https://www.nuget.org/packages/Ben.Demystifier/0.0.43 thanks to @onovotny

**Comment by nicolaihenriksen** [comment]
Very nice! Thank you!
