### ISSUE TITLE
Not compatible with Microsoft.CodeAnalysis.Csharp

### ISSUE THREAD

**Issue by molinch** [benaadams/Ben.Demystifier#36]
First of all thanks a lot, it's very useful to have relevant StackTraces.

Unfortunately I am one of these poor guy that needs to use strongnames. So we used strongnamer which works perfectly. However once you strongname you really need similar versions.

Ben.Demystifier requires System.Reflection.Metadata 1.5.0, which requires System.Collections.Immutable 1.4.0

We also use Microsoft.CodeAnalysis.Csharp, but unfortunately it uses Microsoft.CodeAnalysis.Common 2.4.0, which uses System.Collections.Immutable 1.3.1

So when running the runtime is obviously unhappy.
Do you see a way to make both cohabit?

**Comment by Suchiman** [comment]
@molinch did you try using binding redirects?

**Comment by molinch** [comment]
Yes I did so but also forked the project and changed dependencies: it was more convenient for my use case.
If you want @benaadams we can close the issue, I have a workaround (the fork).

**Comment by molinch** [comment]
Let's close since I have a working solution (forked project).
