### ISSUE TITLE
Some System.Web.Mvc DisplayName methods unresolved

### ISSUE THREAD

**Issue by georgeduckett** [benaadams/Ben.Demystifier#40]
I have a stacktrace line that, after prettifying looks like this:

    at void System.Web.Mvc.Async.AsyncControllerActionInvoker+<>c__DisplayClass21+<>c__DisplayClass2b.<BeginInvokeAction>b__1c(?)+()=>{}

It looks like it can't find a pdb file for System.Web.Mvc, which resides in the Temporary ASP.NET directory. Could that have something to do with it (and is there anything I can do to make the/a pdb available)?

Is this expected output or could this be prettified further?

**Comment by georgeduckett** [comment]
I've managed to figure this one out. It looks like in the TryResolveGeneratedName method if it fails to find the correct method on the declaring type it goes up the chain once and tries again. See this [pull request](https://github.com/benaadams/Ben.Demystifier/pull/41)

**Comment by benaadams** [comment]
Resolved by #41
