### ISSUE TITLE
DLL in NuGet package is not strong-name signed.

### ISSUE THREAD

**Issue by torjoshi** [benaadams/Ben.Demystifier#47]
Please add signing support in project file to allow loading dll from other strong-name signed projects.

**Comment by molinch** [comment]
You can add strongnamer nuget in your project, then it will automatically strongname it.
https://www.nuget.org/packages/StrongNamer/

If that's not a solution it's rather easy to publish your fork, this is what I did, but for other reasons (dependency issues).

**Comment by benaadams** [comment]
Try latest: https://www.nuget.org/packages/Ben.Demystifier/0.0.43 thanks to @onovotny
