### ISSUE TITLE
NuGet dependency mismatch between ValueTuple and framework version

### ISSUE THREAD

**Issue by jankrib** [benaadams/Ben.Demystifier#48]
The Ben.Demystifier package has these dependencies:
![image](https://user-images.githubusercontent.com/956218/35565298-4ea5756c-05bd-11e8-93e9-be0403458d4c.png)

I'm using .NET 4.5 and this is causing issues because `System.ValueTuple 4.4.0` have the dependency `.NETFramework, Version=v4.6.1`

Either Ben.Demystifier should also have `.NETFramework, Version=v4.6.1` or it should use `System.ValueTuple 4.3.1`

**Comment by NickCraver** [comment]
I'd suggest building for both frameworks here - the ValueTuple thing is just a mess platform-wide.

**Comment by benaadams** [comment]
Resolved by https://github.com/benaadams/Ben.Demystifier/pull/63

**Comment by benaadams** [comment]
In version 0.1.1 https://www.nuget.org/packages/Ben.Demystifier/0.1.1
