### ISSUE TITLE
Add extension to demystify StackTrace

### ISSUE THREAD

**Issue by bartsokol** [benaadams/Ben.Demystifier#52]
In some cases we're logging stack traces using `new StackTrace()` and it would be nice to have an extension that would demystify the `StackTrace` alone. For now I've hacked it internally by using `new EnhancedStackTrace(new StackTrace())` but maybe such extension method would be useful for others as well? If you think it's a good idea I can prepare a PR for it.

**Comment by benaadams** [comment]
[`EnhancedStackTrace.Current`](https://github.com/benaadams/Ben.Demystifier/blob/master/src/Ben.Demystifier/EnhancedStackTrace.cs#L13) should already do this?

**Comment by bartsokol** [comment]
Oh, didn't notice that, looks good! I'll try it out instead then, thanks.
