### ISSUE TITLE
Assembly version is missing build and revision numbers

### ISSUE THREAD

**Issue by Euphoric** [benaadams/Ben.Demystifier#53]
Version 0.0.43 is missing assembly version. When this assembly is references in csproj, it shows as

```
<Reference Include="Ben.Demystifier, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a6d206e05440431a, processorArchitecture=MSIL">
  <HintPath>..\packages\Ben.Demystifier.0.0.43\lib\net45\Ben.Demystifier.dll</HintPath>
</Reference>
```

Version 0.0.8 shows as

```
<Reference Include="Ben.Demystifier, Version=0.0.8.0, Culture=neutral, processorArchitecture=MSIL">
  <HintPath>..\packages\Ben.Demystifier.0.0.8\lib\net45\Ben.Demystifier.dll</HintPath>
</Reference>
```

While this is not a problem by itself. It does cause breakage in any libraries that depend on Ben.Demystifier.

For example, if codeessentials.Extensions.Logging.Demystifier is installed, it works fine with 0.0.8 ,but loading exception is thrown for 0.0.43 : 

`Could not load file or assembly 'Ben.Demystifier, Version=0.0.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by Euphoric** [comment]
I did some research around Nerdbank.GitVersioning and found two possible solutions.

First is to increase precision of assembly version in version.json like 

```
  "assemblyVersion": {
    "precision": "build"
  },
```

Second option is to always increase minor version for new release. So next NuGet should be 0.1 not 0.0

**Comment by Euphoric** [comment]
@onovotny You were the one who implemented this, how should this situation be handled?

**Comment by Euphoric** [comment]
Also, it would be great if next release was made soon and 0.0.43 package marked as not-to-be-used. So the version problems don't spread around.

**Comment by clairernovotny** [comment]
It's not missing the numbers, they are set to 0.0 currently. That is controlled by setting it in the version.json file.

Sent from a mobile device, please excuse brevity and typos
________________________________

**Comment by Euphoric** [comment]
Thanks @onovotny for clarifying. But that is not the problem. The problem is that previous NuGet package 0.0.8.0 has assembly version 0.0.8.0. And next version 0.0.43.0 has version 0.0.0.0 . So if a 3rd party library depends on 0.0.8.0 , but 0.0.43.0 is installed, then .NET thinks old version is present based on assembly version and fails with exception.

Either increase precision of assembly version to include at least build number , or make sure to always increase minor version when releasing new NuGet package.

**Comment by benaadams** [comment]
Prob should release a 0.1

**Comment by clairernovotny** [comment]
0.0.43.0 us a higher version than 0.0.8. The issue is normal binding redirects than desktop.net requires. They sound be automatically added by msbuild though.

You'll hit this no matter what version you use since it requires an exact match without the redirect.

Sent from a mobile device, please excuse brevity and typos
________________________________

**Comment by Euphoric** [comment]
@onovotny That is not true. 0.0.43 is higher NuGet version but it is not higher Assembly version.

Here is sample project 
[BenDemystifyTest.zip](https://github.com/benaadams/Ben.Demystifier/files/1707658/BenDemystifyTest.zip)

It has codeessentials.Extensions.Logging.Demystifier installed. This is built against 0.0.4.0 , but 0.0.8.0 is installed and it works. But after upgrading to 0.0.43 , the exception I posted in top comment is thrown. So it is not exact match and no redirect is needed. But only if Assembly version is greater than 0.0.4.0, which it isn't for 0.0.43 NuGet package.

**Comment by clairernovotny** [comment]
That's because it wasn't strong named.

Sent from a mobile device, please excuse brevity and typos
________________________________

**Comment by clairernovotny** [comment]
Strong naming is a breaking change, so you'd need to recompile once with the latest version. Before it wasn't strong named.

Sent from a mobile device, please excuse brevity and typos
________________________________

**Comment by benaadams** [comment]
Published https://www.nuget.org/packages/Ben.Demystifier/0.1.0

**Comment by benaadams** [comment]
Submitted updates to various projects https://github.com/nblumhardt/serilog-enrichers-demystify/pull/6, https://github.com/MNie/Log4Net.Demystifier/pull/1, https://github.com/twenzel/Demystify.Everything/pull/6 (codeessentials)

**Comment by benaadams** [comment]
Should be resolved

**Comment by dhazel** [comment]
My issue #87 may be related.
