### ISSUE TITLE
Missing Assemblies because of System.ValueTuple?

### ISSUE THREAD

**Issue by abergs** [benaadams/Ben.Demystifier#59]
Probably not a bug, but maybe a good thing to put in readme?
I installed this on a net 461 project yesterday. We ran into weird problems, for example a referenced project couldnt find System.Net.Http 4.2.0.0.

I thought maybe net462 was needed so we tried to upgrade. Still the asme problem.

Tried to Run Add-BindingRedirect etc. 
Tried upgrading all the way to net471.

Never got it to run. If I removed Ben.Demystifier it all worked again.

Any clues on how to resolve this?

**Comment by benaadams** [comment]
Resolved by https://github.com/benaadams/Ben.Demystifier/pull/63

**Comment by benaadams** [comment]
In version 0.1.1 https://www.nuget.org/packages/Ben.Demystifier/0.1.1
