### ISSUE TITLE
File names are missing in the stack trace when assemblies are built with /pathmap

### ISSUE THREAD

**Issue by SergeyTeplyakov** [benaadams/Ben.Demystifier#61]
If the dll is built with /patmap option (see [Deterministic Builds in Roslyn](http://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html) for more details), then the file names in the original stack trace could be a bit weird like this: `\.\Sources\Foo\Bar.cs`. 

The Demystifier tries to get the full path for such a frame, fails doing that and skips the file name altogether.

**Comment by benaadams** [comment]
Resolved
