### ISSUE TITLE
Path separater is "wrong" on Windows

### ISSUE THREAD

**Issue by erikbra** [benaadams/Ben.Demystifier#65]
Maybe this is "as designed", but I noticed that Ben.Demystifier uses forward-slashes for path separators, and not backslashes, as the normal exception stack trace on Windows. It this intentional, for it to be the same across all platforms, or unintentional?

**Comment by johnrutherford** [comment]
Yeah, I just noticed this too. It also replaces spaces in the path with "%20". So it's like the path is being formatted as a URL.

**Comment by onyxmaster** [comment]
It converts the backtick characters to %60 too. It appears that "url" treatment didn't go so well for paths 😄

**Comment by bruno-garcia** [comment]
~Can be closed:~
~Fixed on 0.1.4 PR #82~

The PR fixed something else:

`[InlineData(@"d:\Public Files+50%.Done\Src\Foo`1.cs", @"d:/Public Files+50%.Done/Src/Foo`1.cs", false)]`

**Comment by onyxmaster** [comment]
I would like to indicate that my PR (#82) was not intended to "fix" the path separators (I consider forward slashes as path separators as a feature, not a bug), it merely made them consistent along with proper handling of special characters.
