### ISSUE TITLE
NuGet package adds duplicate references

### ISSUE THREAD

**Issue by riley-van-hengstum** [benaadams/Ben.Demystifier#68]
I would like to use this, but somehow installing the NuGet package adds a lot of duplicate references to my projects for system packages such as `System.Collections`, `System.ComponentModel`, etc.

Using .NET Framework 4.6.2 in my projects. For example, the `System.Collections` package referenced is:

`System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Collections.dll`

Installing the Demystifier NuGet package adds the duplicate reference:

`System.Collections, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files (x86)\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\ref\System.Collections.dll`

Anything I can do about that?

**Comment by btecu** [comment]
What's the status of this?

**Comment by riley-van-hengstum** [comment]
Closing this for it's a stale issue.
