### ISSUE TITLE
Fails when method does not have ReturnParameter

### ISSUE THREAD

**Issue by exyi** [benaadams/Ben.Demystifier#9]
When there is a dynamically compiled lambda expression in the path, the Demystifier fails on https://github.com/benaadams/Ben.Demystifier/blob/master/src/Ben.Demystifier/EnhancedStackTrace.Frames.cs#L162

Because the `lambda_method` has `null` in the `ReturnParameter` (I don't know why) and `GetParameter` method fails on that with `NullReferenceException`.

**Comment by benaadams** [comment]
Fixed an new package released to NuGet
